origin:
  oss:
    enabled: true
    type: ali
    bucket: origin-platform.oss-cn-beijing.aliyuncs.com
    bucket-name: origin-platform
    end-point: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJEggzXoCWKc1z2MKXB
    access-key-secret: vuudgh9msatlleHSl3kYgmT3ofBtjq








